name: CrazyChats
main: de.st_ddt.crazychats.CrazyChats
author: ST-DDT
version: 1.199
website: http://dev.bukkit.org/server-mods/crazychats/
# requires CrazyCore v10.5 or later
depend: [CrazyCore]
softdepend: [TagAPI]
description: >
            CrazyChats add chat channels and many usefull features to your chat.
commands:
  colorhelp:
    description: Shows a string displaying all chat formats.
    usage: /<command>
  tell:
    description: Chat to the given player.
    usage: /<command> <Players> <Message>
    aliases: [pm,msg,message]
  answer:
    description: Answer to the last private message recieved.
    usage: /<command> <Message>
    aliases: [re,reply]
  say:
    description: Send a broadcast to the entire server.
    usage: /<command> <Message>
  chatto:
    description: Chat to the given players only.
    usage: /<command> [Players]
  chatadd:
    description: Add the given players to the private chat channel targets.
    usage: /<command> <Players>
  chatremove:
    description: Remove the given players from the private chat channel targets.
    usage: /<command> <Players>
  chatchannel:
    description: Get/Change your current chat channel.
    usage: /<command> [Channel]
  muteplayer:
    description: Mute a player.
    usage: /<command> <Player...>
  unmuteplayer:
    description: Unmute a player.
    usage: /<command> <Player...>
  mutechannel:
    description: Mute a channel.
    usage: /<command> <Channel...>
  unmutechannel:
    description: Unmute a channel.
    usage: /<command> <Channel...>
  muteall:
    description: Mute all channels.
    usage: /<command>
  clearchat:
    description: Clear the players chat history.
    usage: /<command> [Player/*]
  serversilence:
    description: Silence all public chat for a certain amount of time.
    usage: /<command> [Date/Duration]
    usage: [silence,globalmute]
  crazychats:
    description: Plugin Main Menu
    usage: /<command> <Subcommands...>
    aliases: [crazychat,cchats,cchat]
permissions:
  crazychats.*:
    description: Access to all commands
    default: false
    children:
      crazychats.mode: true
      crazychats.broadcastchannel.talk: true
      crazychats.globalchannel.talk: true
      crazychats.worldchannels.remotetalk: true
      crazychats.worldchannels.talk: true
      crazychats.localchannel.talk: true
      crazychats.adminchannel.talk: true
      crazychats.adminchannel.listen: true
      crazychats.talk: true
      crazychats.player.displayname.self: true
      crazychats.player.displayname.other: true
      crazychats.player.headname.self: true
      crazychats.player.headname.other: true
      crazychats.player.listname.self: true
      crazychats.player.listname.other: true
      crazychats.player.mute: true
      crazychats.player.silence: true
      crazychats.player.silence.adminbypass: true
      crazychats.player.unmute: true
      crazychats.coloredchat: true
      crazychats.chatspy: true
      crazychats.unmutable: true
      crazychats.nocleaning: true
      crazychats.clearchat: true
      crazychats.serversilence: true
      crazychats.serversilence.bypass: true
      crazychats.customchannel.admin: true
  crazychats.mode:
    description: Allow changing plugin options.
    default: op
  crazychats.broadcastchannel.talk:
    description: Allow chatting in Broadcast channel.
    default: op
  crazychats.globalchannel.talk:
    description: Allow chatting in Global channel.
    default: op
  crazychats.worldchannels.remotetalk:
    description: Allow chatting in all World channels (from other world).
    default: op
#  crazychats.worldchannel.WORLD.remotetalk:
#    description: Allow chatting in WORLD's World channel (from other world).
#    default: op
  crazychats.worldchannels.talk:
    description: Allow chatting in all World channels (current world).
    default: true
#  crazychats.worldchannel.WORLD.talk:
#    description: Allow chatting in WORLD's World channel (current world).
#    default: true
  crazychats.localchannel.talk:
    description: Allow chatting in Local channel.
    default: true
  crazychats.adminchannel.talk:
    description: Allow chatting in Admin channel.
    default: op
    children:
      crazychats.adminchannel.listen: true
  crazychats.adminchannel.listen:
    description: Allow listening to Admin channel.
    default: op
  crazychats.talk:
    description: Allow chatting.
    default: true
  crazychats.player.displayname.self:
    description: Allow changing your own display name.
    default: op
  crazychats.player.displayname.other:
    description: Allow changing other player's display names.
    default: op
  crazychats.player.headname.self:
    description: Allow changing your own head name.
    default: op
  crazychats.player.headname.other:
    description: Allow changing other player's head name.
    default: op
  crazychats.player.listname.self:
    description: Allow changing your own list name.
    default: op
  crazychats.player.listname.other:
    description: Allow changing other player's list name.
    default: op
  crazychats.player.silence:
    description: Allow silencing/globally muting a player.
    default: op
  crazychats.player.silence.adminbypass:
    description: Allow silencing/globally muting a player bypassing the max silence limit.
    default: op
  crazychats.player.mute:
    description: Allow muting a player for another player.
    default: op
  crazychats.player.unmute:
    description: Allow unmuting a player for another player.
    default: op
  crazychats.coloredchat:
    description: Allow colored chat.
    default: op
  crazychats.chatspy:
    description: Show all messages to this player.
    default: false
    children:
      crazychats.worldchannels.remotetalk: true
      crazychats.worldchannels.talk: true
      crazychats.localchannel.talk: true
      crazychats.talk: true
  crazychats.unmutable:
    description: This player cannot be muted.
    default: op
  crazychats.nocleaning:
    description: This player's chat messages will not be cleaned.
    default: op
  crazychats.clearchat:
    description: Allow clearing the players chat history.
    default: op
  crazychats.serversilence:
    description: Allow silencing all public chat for a certain amount of time.
    default: op
  crazychats.serversilence.bypass:
    description: Allow public chatting while server is silenced.
    default: op
  crazychats.customchannel.admin:
    description: Allow modifing all custom channels.
    default: op