name: CrazySpawner
main: de.st_ddt.crazyspawner.CrazySpawner
author: ST-DDT
version: 3.13.1
website: http://dev.bukkit.org/server-mods/crazyspawner/
# requires CrazyCore v10.2.1 or later
depend: [CrazyCore]
description: >
            CrazySpawner spawn and remove mobs where ever you like.
commands:
  crazyspawn:
    description: Spawn living Creatures...
    usage: /<command> <creature:Creature> [amount:Integer] [repeat:Integer] [interval:Duration] [delay:Duration] [synced:Boolean] [chunkloadrange:Integer] [creaturemaxcount:Integer [creaturerange:Double]] [playermincount:Integer [playerrange:Double]] [blockingrange:Double] [allowdespawning:Boolean] [peaceful:Boolean] [location:Location] [health:Integer] [showHealth:Boolean]
    aliases: [crazymobs, cms, spawnmob]
  crazykill:
    description: Kill living Creatures...
    usage: /<command> <Range> [monster:Boolean] [animals:Boolean] [golems:Boolean] [villagers:Boolean] [bosses:Boolean] [location:Location]
    aliases: [butcher, killall, cmk, killmob]
  crazycreaturespawner:
    description: Change spawner types.
    usage: /<command> <Creature>
    aliases: [spawner, creaturespawner, ccs]
  crazytheendautorespawn:
    description: Create auto respawn tasks for EnderDragons and EnderCrystals.
    usage: /<command> [interval:Duration] [world:World] [chunkloadrange:Integer]
    aliases: [theendautorespawn, ctearespawn, tearespawn,ctear,tear]
  crazyspawner:
    description: Plugin Mainmenu
    usage: /<command> [Subcommands...]
    aliases: [cspawner]
permissions:
  crazyspawner.*:
    description: Access to all commands
    default: false
    children:
      crazyspawner.spawn: true
      crazyspawner.kill: true
      crazyspawner.creaturespawner: true
      crazyspawner.theendautorespawn: true
      crazyspawner.list: true
      crazyspawner.remove: true
  crazyspawner.spawn:
    description: Allow spawning of creatures
    default: op
  crazyspawner.kill:
    description: Allow killing of creatures
    default: op
  crazyspawner.creaturespawner:
    description: Allow changing of creature spawners.
    default: op
  crazyspawner.theendautorespawn:
    description: Allow creating auto respawn tasks for EnderDragons and EnderCrystals.
    default: op
  crazyspawner.list:
    description: Allow listing spawn tasks.
    default: op
  crazyspawner.list:
    description: Allow removing spawn tasks.
    default: op