name: CrazySpawner
main: de.st_ddt.crazyspawner.CrazySpawner
author: ST-DDT
version: 3.5
website: http://dev.bukkit.org/server-mods/crazyspawner/
# requires CrazyCore v10.0.3 or later
depend: [CrazyCore]
description: >
            CrazySpawner spawn and remove mobs where ever you like.
commands:
  crazyspawn:
    description: Spawn living Creatures...
    usage: /<command> "<creature:Creature> [amount:Integer] [repeat:Integer] [interval:Duration] [delay:Duration] [creaturemaxcount:Integer [creaturerange:Double]] [playermincount:Integer [playerrange:Double]] [location:Location]
    aliases: [crazymobs, cms]
  crazykill:
    description: Kill living Creatures...
    usage: /<command> <Range> [monster:Boolean] [animals:Boolean] [golems:Boolean] [villagers:Boolean] [bosses:Boolean] [location:Location]
    aliases: [butcher, killall, cmk]
  crazycreaturespawner:
    description: Change spawner types.
    usage: /<command> <Creature>
    aliases: [spawner, crazyspawner, ccs]
  crazyspawner:
    description: Plugin Mainmenu
    usage: /<command> [Subcommands...]
permissions:
  crazyspawner.*:
    description: Access to all commands
    default: false
    children:
      crazyspawner.spawn: true
      crazyspawner.kill: true
  crazyspawner.spawn:
    description: Allow spawning of Creatures
    default: op
  crazyspawner.kill:
    description: Allow killing of Creatures
    default: op