name: CrazyCore
main: de.st_ddt.crazycore.CrazyCore
author: ST-DDT
version: 10.7.7
website: http://dev.bukkit.org/server-mods/crazycore/
softdepend: [PermissionsEx,GroupManager,PermissionsBukkit,bPermissions,Vault]
description: >
            CrazyPlugin Core needed for all CrazyPlugins.
commands:
  crazylist:
    description: Shows all enabled CrazyPlugins.
    usage: /<command>
  crazycore:
    description: Some further information and commands.
    usage: /<command> [Subcommands...]
    aliases: [cc,ccore]
  crazylanguage:
    description: Change languages
    usage: /<command> [Language]
    aliases: [language]
  crazypage:
    description: Scroll through pages.
    usage: /<command> [+/-/pagenumber]
    aliases: [page,cpage]
  crazypipe:
    description: Push data in pipe commands
    usage: /<command> <$PresetList>/<Arg1>, <Arg2>, ... [> PipeCommand]
    aliases: [pipe,cpipe]
permissions:
  crazy*.*:
    description: Access to all permissions in all CrazyPlugins.
    default: op
    children:
      crazycore.protectedplayer: true
      crazylanguage.advanced: true
      crazypipe.use: true
  crazycore.*:
    description: Access to all permissions belonging to this plugin.
    default: op
    children:
      crazycore.commandinfo: true
      crazycore.help: true
      crazycore.info: true
      crazycore.list: true
      crazycore.logger: true
      crazycore.mode: true
      crazycore.mode.*: true
      crazycore.mode.checkforupdates: true
      crazycore.mode.loaduserlanguages: true
      crazycore.mode.wipeplayerbans: true
      crazycore.mode.wipeplayerworldfiles: true
      crazycore.params.invisibleplayers: true
      crazycore.player.associates: true
      crazycore.player.delete.other: true
      crazycore.player.delete.protected: true
      crazycore.player.delete.self: true
      crazycore.player.info: true
      crazycore.player.ipsearch: true
      crazycore.protectedplayer: true
      crazycore.protectedplayer.accesswarn: true
      crazycore.protectedplayer.illegalaccesswarn.staff: true
      crazycore.protectedplayer.illegalaccesswarn.user: true
      crazycore.reload: true
      crazycore.reload.*: true
      crazycore.reload.config: true
      crazycore.save: true
      crazycore.updatecheck: true
      crazycore.wipecommands: true
      crazycore.wipefilepaths: true
      crazylanguage.advanced: true
      crazypipe.use: true
  crazycore.commandinfo:
    description: Allow searching for commands and displaying detailed information about it.
    default: op
  crazycore.help:
    description: Allow accessing the plugin help.
    default: op
  crazycore.info:
    description: Allow showing information about this plugin.
    default: op
  crazycore.list:
    description: Allow showing all enabled CrazyPlugins.
    default: op
  crazycore.logger:
    description: Allow configuring the plugin logger.
    default: op
  crazycore.mode:
    description: Allow changing plugin modes.
    default: op
  crazycore.mode.*:
    description: Allow changing all plugin modes.
    default: op
    children:
      crazycore.mode.checkforupdates: true
      crazycore.mode.loaduserlanguages: true
      crazycore.mode.wipeplayerbans: true
      crazycore.mode.wipeplayerworldfiles: true
  crazycore.mode.checkforupdates:
    description: Allow changing checkForUpdates mode.
    default: op
  crazycore.mode.loaduserlanguages:
    description: Allow changing loadUserLanguages mode.
    default: op
  crazycore.mode.wipeplayerbans:
    description: Allow changing wipePlayerBans mode.
    default: op
  crazycore.mode.wipeplayerworldfiles:
    description: Allow changing wipePlayerWorldFiles mode.
    default: op
  crazycore.params.invisibleplayers:
    description: Allow this player to use invisible players in commands.
    default: op
  crazycore.player.associates:
    description: Allow listing all known associates of a player (recursive) (stored by CrazyPlugins).
    default: op
  crazycore.player.delete.other:
    description: Allow full deletion of other player's data.
    default: op
  crazycore.player.delete.protected:
    description: Allow full deletion of protected player's data.
    default: op
  crazycore.player.delete.self:
    description: Allow full deletion of the own player's data.
    default: op
  crazycore.player.info:
    description: Allow displaying of all available information about a player (stored by CrazyPlugins).
    default: op
  crazycore.player.ipsearch:
    description: Allow searching for players connected to this ip (stored by CrazyPlugins).
    default: op
  crazycore.protectedplayer:
    description: Forces additional protection to this player.
    default: op
  crazycore.protectedplayer.accesswarn:
    description: Player will be informed if a player tries to access a protected player.
    default: op
  crazycore.protectedplayer.illegalaccesswarn.staff:
    description: Player will be warned with detailed information if a player tries to illegally access a protected player.
    default: op
  crazycore.protectedplayer.illegalaccesswarn.user:
    description: Player will be warned if a player tries to illegally access a protected player.
    default: true
  crazycore.reload:
    description: Allow reloading the plugin.
    default: op
  crazycore.reload.*:
    description: Allow reloading the entire plugin.
    default: op
  crazycore.reload.config:
    description: Allow reloading the config of this plugin.
    default: op
  crazycore.save:
    description: Allow saving plugin.
    default: op
  crazycore.updatecheck:
    description: Allow checking for updates and get informed if updates are available.
    default: op
  crazycore.wipecommands:
    description: Allow viewing and changing of all commands executed to wipe a player.
    default: op
  crazycore.wipefilepaths:
    description: Allow viewing and changing of all files deleted to wipe a player.
    default: op
  crazylanguage.advanced:
    description: Allow changing default languages or language reloads.
    default: op
  crazypipe.use:
    description: Allow usage of crazypipes.
    default: op