name: CrazyAnnouncer
main: de.st_ddt.crazyannouncer.CrazyAnnouncer
author: ST-DDT
version: 1.9.0
website: http://dev.bukkit.org/server-mods/crazyannouncer/
# requires CrazyCore v10.7.8 or later
depend: [CrazyCore]
description: >
            Announce messages and commands in defined intervals and on special events.
commands:
  crazyannouncer:
    description: Create/show delete an announcement
    usage: /<command> <Player>
    aliases: [announcer,announce,crazyannounce]
permissions:
  crazyannouncer.*:
    description: Access to all commands
    default: false
    children:
      crazyannouncer.create: true
      crazyannouncer.list: true
      crazyannouncer.delete: true
  crazyannouncer.create:
    description: Allow creating an new announcement
    default: op
  crazyannouncer.list:
    description: Allow listing all announcements
    default: op
  crazyannouncer.delete:
    description: Allow deleting announcements
    default: op
    